name: ShowYourPrefix
version: 1.0.0
main: me.cplt.Main
api-version: '1.21.8'
author: CPLT
description: ShowYourPrefix - 玩家自定义头衔插件

commands:
  cplt:
    description: 头衔管理核心指令
    usage: /<command> [off|on|list|reload]
    permission-message: §c你没有权限使用该指令！

permissions:
  cplt.use:
    description: 玩家申请头衔的基础权限
    default: true
  cplt.admin:
    description: 管理员禁用/启用/重载插件的权限
    default: op